### ISSUE TITLE
React Integration requires unnecessary work

### ISSUE THREAD

**Issue by WavyWalk** [storyblok/richtext#144]
We migrated from @storyblok/react to use richtext in our project - because of the deprecation warning suggesting to use @storyblok/richtext.

Migration brought several surprises, that some things do not work (e.g. styles passed as string). 

Biggest one is - it does not work out of the box, we had to find out that we need to reimplement stuff from the playground.

For DX purposes why does package not contain code in playgrounds by default in the package?

It could e.g. export ReactRichtext, which already has whole basics to make it work.

Or just at least state directly in the readme:
"To make it work with react, implement the code in the playground.", so it could save time for people wondering why things do not work.

**Comment by alvarosabu** [comment]
Hi @WavyWalk thanks for reaching out and providing feedback, you are right, I'm sorry about the confusion, let me help clear things out:

I'm currently working on integrating the `@storyblok/richtext` package directly on the `@storyblok/react` SDK https://github.com/storyblok/storyblok-react/pull/1243. This will export 2 high-level DX APIs:
- A hook `useStoryblokRichtextResolver`
- A component `StoryblokRichtextResolver` 

Which under the hood, formats the HTML attributes into JSX like the playground does.

> Or just at least state directly in the readme:
> "To make it work with react, implement the code in the playground.", so it could save time for people wondering why things do not work.

I'm going to update the docs with this info.
